_extends: gh-plumbing:.github/commons-settings.yml
repository:
  name: workstation
  description: Local Workstation Configuration
  homepage: https://nolte.github.io/workstation/
  topics: templating, dotfile, workstation
