site_name: Workstation (dotfiles)
theme:
  name: material
docs_dir: docs/
repo_name: 'nolte/workstation'
repo_url: 'https://github.com/nolte/workstation'
plugins:
  - include-markdown
markdown_extensions:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.highlight:
  - toc:
      permalink: True
extra_css:
  - css/overwrite.css

nav:
  - Home: 'index.md'
  - 'Configurations':
    - 'Package Manager (asdf)': 'configurations/package-manager.md'
    - 'Git': 'configurations/git.md'
    - 'zsh': 'configurations/zsh.md'
    - 'Taskfile' : 'configurations/taskfile.md'
