site_name: Workstation (dotfiles)
theme:
  name: material
docs_dir: docs/
repo_name: 'nolte/workstation'
repo_url: 'https://github.com/nolte/workstation'
plugins:
  - search
  - include-markdown
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
          nav_translations:
            Home: Start
            References: Referenzen
            Package manager (asdf): Paketmanager (asdf)
markdown_extensions:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.highlight:
  - toc:
      permalink: True
extra_css:
  - css/overwrite.css

nav:
  - Home: index.md
  - References:
    - Package manager (asdf): configurations/package-manager.md
    - Git: configurations/git.md
    - zsh: configurations/zsh.md
    - Taskfile: configurations/taskfile.md
