on:
  release:
    types: [published]

jobs:
  refresh_presentation_branch:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-cd-refresh-master.yml@v1.1.10
    with:
      target_branch: main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
